# Theme settings
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: HRV Toolkit
            image:
        nav:
            - item_name: Source Code
              item_url: 'https://github.com/arthurkuhn/hrvtoolkit'
    footer:
        content:
            logo:
                text: HRV Toolkit
                image:
            copyright: #Copyright &copy; 2017. - Project name <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: https://github.com/arthurkuhn/hrvtoolkit
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/